swagger: '2.0'
info:
  version: beta
  title: Customer Survey API
  description: >
    Customer survey API gives you access to generated surveys for customer, post
    captured response to survey and ability to generate surveys based on
host: api.asse.co
basePath: /customer-survey
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Templates
    description: Working with survey templates
  - name: Surveys
    description: Working with surveys
paths:
  /templates:
    get:
      summary: Operation returns list of surveys templates with basic survey information.
      operationId: Templates_GetList
      x-asee-tags:
        - Shapeable
        - Sortable
        - Pageable
      tags:
        - Templates
      parameters:
        - $ref: '#/parameters/page-size-param'
        - $ref: '#/parameters/page-number-param'
        - $ref: '#/parameters/sort-order-param'
        - $ref: '#/parameters/sort-type-param'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/surveys'
        default:
          $ref: '#/responses/default-error-response'
  '/templates/{template-id}':
    get:
      summary: Operation generates survey for specific customer based on surveys template id
      operationId: Templates_Get
      x-asee-tags:
        - Shapeable
        - Sortable
        - Pageable
      tags:
        - Templates
      parameters:
        - $ref: '#/parameters/template-id-param'
        - $ref: '#/parameters/survey-request-param'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/survey'
        '440':
          description: Business problem
          schema:
            $ref: '#/definitions/business-problem'
  /surveys:
    post:
      summary: Operation captures response to a survey
      operationId: Surveys_CaptureResponse
      x-asee-tags:
        - Shapeable
        - Sortable
        - Pageable
      tags:
        - Surveys
      parameters:
        - $ref: '#/parameters/survey-response-param'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/command-result'
        '440':
          description: Business problem
          schema:
            $ref: '#/definitions/business-problem'
  '/surveys/{survey-id}':
    get:
      summary: Operation returns the completed survey with questions and answers
      operationId: Surveys_GetSurveyDetails
      x-asee-tags:
        - Shapeable
        - Sortable
        - Pageable
      tags:
        - Surveys
      parameters:
        - $ref: '#/parameters/survey-id-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/survey'
        '400':
          $ref: '#/responses/validation-problem-response'
parameters:
  page-size-param:
    name: page-size
    in: query
    description: Gets or sets the size of the page.
    type: integer
    format: int32
    required: false
  page-number-param:
    name: page-number
    in: query
    description: Gets or sets the page number.
    type: integer
    format: int32
  sort-order-param:
    name: sort-order
    in: query
    required: false
    description: Gets or sets the sort order - direction (ASC or DESC).
    type: string
  sort-type-param:
    name: sort-type
    in: query
    required: false
    description: Gets or sets the name of the column for sorting.
    type: string
  survey-response-param:
    name: survey-response
    in: body
    required: true
    description: ''
    schema:
      $ref: '#/definitions/survey-response'
  survey-request-param:
    name: survey-request
    in: body
    required: true
    description: ''
    schema:
      $ref: '#/definitions/survey-request'
  survey-id-param:
    name: survey-id
    in: path
    description: Id of the survey
    required: true
    type: string
  template-id-param:
    name: template-id
    in: path
    description: Id of the survey template
    required: true
    type: string
responses:
  validation-problem-response:
    description: 'Your request was not constructed properly. Response contains the list of validation errors for each invalid element of your request. For complete list of possible validation errors see [validation errors]() classification.'
    schema:
      $ref: '#/definitions/validation-problem'
  default-error-response:
    description: 'Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling]()'
definitions:
  survey-response:
    description: Response to survey with customer answers to survey
    properties:
      id:
        description: Command identifier
        type: string
      customer-id:
        description: 'Business identifier of the party in the core system. It can be either core generated, or imported.'
        type: string
      template-id:
        description: Template identifier
        type: string
      answers:
        description: List of answers
        items:
          $ref: '#/definitions/question-with-answer'
        type: array
    required:
      - customer-id
      - template-id
    type: object
  survey-request:
    description: Survey request
    properties:
      customer-id:
        description: 'Business identifier of the party in the core system. It can be either core generated, or imported.'
        type: string
    required:
      - customer-id
    type: object
  question-with-answer:
    description: Answer
    properties:
      question-id:
        description: Question identifier
        type: string
      answer:
        description: Answer
        $ref: '#/definitions/answer'
    required:
      - question-id
    type: object
  surveys:
    description: List of surveys
    properties:
      total-count:
        description: Gets or sets the total count.
        format: 'int32,'
        type: integer
      page-size:
        description: Gets or sets the size of the page.
        format: int32
        type: integer
      page-number:
        description: Gets or sets the page number.
        format: int32
        type: integer
      total-pages:
        description: Gets or sets the total pages.
        format: int32
        type: integer
      items:
        description: List of surveys with basic survey information.
        items:
          $ref: '#/definitions/survey-info'
          type: array
      navigations:
        description: Links to related resources.
        items:
          $ref: '#/definitions/link'
        type: array
      commands:
        description: Available commands in current context.
        items:
          $ref: '#/definitions/link'
          type: array
      uri:
        description: URI
        type: string
    type: object
  survey:
    description: Completed survey
    properties:
      survey-id:
        description: Survey identifier
        type: string
      date-created:
        description: Created on
        format: date-time
        type: string
      survey-info:
        description: Basic survey info
        $ref: '#/definitions/survey-info'
      survey-sections:
        description: List of sections
        items:
          $ref: '#/definitions/survey-section'
        type: array
    type: object
  survey-info:
    description: Basic informations about survey
    properties:
      template-id:
        description: Uniquely identifies surveys template
        type: string
      title:
        description: Human readable name of the survey by which it is best recognized.
        type: string
      description:
        description: A textual description of the survey
        type: string
      date-published:
        description: Publication date
        format: date-time
        type: string
      uri:
        description: URI
        type: string
    type: object
  survey-section:
    description: Survey section
    properties:
      survey-section-id:
        description: Survey section identifier
        type: string
      order:
        description: Section order in survey
        format: int32
        type: integer
      title:
        description: Section title
        type: string
      description:
        description: Textual description about section
        type: string
      survey-sections:
        description: List of child sections
        items:
          $ref: '#/definitions/survey-section'
        type: array
      questions:
        description: List of questions
        items:
          $ref: '#/definitions/question'
        type: array
    type: object
  question:
    description: Question
    properties:
      question-id:
        description: Question identifier
        type: string
      order:
        description: Order of question in a survey
        format: int32
        type: integer
      title:
        description: Question title
        type: string
      description:
        description: A textual description of the question
        type: string
      kind:
        description: Question kind.
        type: string
      question-options:
        additionalProperties:
          type: string
        description: Dictionary containes possible answers on question if question type is options or multiple-options.
        type: object
      units-of-measure:
        description: 'Units of measure. Example for currency would be: USD, EUR, CHF. Example for length: km, m, cm'
        items:
          type: string
        type: array
      is-mandatory:
        description: Is question required or mandatory
        type: boolean
      answer:
        description: Answer
        $ref: '#/definitions/answer'
    type: object
  answer:
    description: Answer
    properties:
      text:
        description: This property contains answer if question type is text
        type: string
      bool-answer:
        description: This property contains answer if question type is bool
        type: boolean
      numeric:
        description: This property contains answer if question type is numeric
        format: double
        type: number
      date:
        description: This property contains answer if question type is date
        format: date-time
        type: string
      unit-of-measure:
        description: This property contains selected unit-of-measure
        type: string
      option-id:
        description: This property contains answer if question type is options or multiple-options
        type: string
    type: object
  link:
    properties:
      href:
        description: Gets or sets the href.
        type: string
      rel:
        description: Gets or sets the rel.
        type: string
    type: object
  command-result:
    description: ''
    properties:
      id:
        description: 'Gets or sets the id of created, updated or deleted entity.'
        type: string
      created-record-status:
        description: 'Gets or sets the created, updated, deleted record status.'
        type: string
    type: object
  validation-problem:
    type: array
    items:
      type: object
      properties:
        field:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
    example:
      - field: phone-number
        errors:
          - error: invalid-format
            message: Format for this field is invalid
          - error: max-length
            message: Content exceeds maximum alowed length
      - field: account-number
        errors:
          - error: check-digit-invalid
            message: Check digit is invalid for this field
  business-problem:
    properties:
      type:
        type: string
      title:
        type: string
      details:
        type: string
    type: object
