swagger: '2.0'
info:
  version: beta
  title: Correspondence API
  description: |
    Correspondence API handles the automated generation of batches of pre-formatted correspondence, typically integrating customer/product specific data in correspondence templates for variable aspects of content. Channel applications can use this API to deliver alerts, reminders, advices, past due notices, announcements, campaign offers, statements and other arrangement reports. With Correspondence API you can: 
       - List communications for delivery 
       - List archived communications 
       - Report communication delivery status 
       - Render content with template
host: 'api.asee.co'
basePath: /correspondence
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - description: Working with communications
    name: Communications
  - description: Working with documents
    name: Documents
  - description: Working with communication summaries
    name: Communication summaries
paths:
  /communications:
    get:
      summary: Get the list of communications that are no longer waiting for delivery.
      tags:
        - Communications
      operationId: Communications_GetList
      parameters:
        - $ref: '#/parameters/start-time-param'
        - $ref: '#/parameters/end-time-param'
        - $ref: '#/parameters/contact-medium-param'
        - $ref: '#/parameters/status-param'
        - $ref: '#/parameters/search-text-param'
        - $ref: '#/parameters/customer-number-param'
        - $ref: '#/parameters/conversation-type-param'
        - $ref: '#/parameters/page-size-param'
        - $ref: '#/parameters/page-number-param'
        - $ref: '#/parameters/sort-order-param'
        - $ref: '#/parameters/sort-by-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/communication-list'
        default:
          $ref: '#/responses/default-error-response'
      x-asee-tags:
        - Pageable
        - Sortable
    post:
      summary: Initiates the communication delivery.
      tags:
        - Communications
      operationId: Communications_Create
      parameters:
        - description: The initiate communication delivery command.
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/initiate-communication-command'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/command-result'
        default:
            $ref: '#/responses/default-error-response'
      x-asee-tags: []
  /communications/{communication-id}/status:
    put:
      summary: Update communication status.
      tags:
        - Communications
      operationId: Communications_UpdateStatus
      parameters:
        - $ref: '#/parameters/communication-id-param'
        - name: cmd
          in: body
          description: Update communication command.
          required: true
          schema:
            $ref: '#/definitions/update-communication-status-command'
      responses:
        '200':
          description: Communication status updated
          schema:
            $ref: '#/definitions/command-result'
        default:
          $ref: '#/responses/default-error-response'
      x-asee-tags: []
  /communications/{communication-id}:
    get:
      summary: Gets the communication details.
      tags:
        - Communications
      operationId: Communications_Get
      parameters:
        - $ref: '#/parameters/communication-id-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/communication'
        default:
            $ref: '#/responses/default-error-response'
      x-asee-tags: []
  /communication-summaries:
    get:
      summary: Gets the communication delivery status.
      tags:
        - Communication summaries
      operationId: CommunicationSummaries_GetList
      parameters:
        - $ref: '#/parameters/contact-medium-param'
        - $ref: '#/parameters/status-param'
        - $ref: '#/parameters/customer-number-param'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/communication-summary-list'
        default:
            $ref: '#/responses/default-error-response'
      x-asee-tags: []
  /documents:
    post:
      summary: Renders the document based on specified template.
      tags:
        - Documents
      operationId: Documents_Create
      parameters:
        - description: Renders document.
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/create-document-command'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/document'
        default:
            $ref: '#/responses/default-error-response'
      x-asee-tags: []
parameters:
  start-time-param:
    name: start-time
    in: query
    description: Time of the first communication to be returned.
    type: string
    required: false
    format: date-time  
  end-time-param:
    name: end-time
    in: query
    description: Date of last transaction. Default value is today.   
    type: string
    required: false
    format: date-time
  contact-medium-param:
    name: contact-medium
    in: query
    description: Contact medium designated for the delivery of the communication
    type: string
    required: true
    enum:
      - smartphone-push
      - email
      - virtual-inbox
      - sms 
  page-size-param:
    name: page-size
    in: query
    description: Number of items on a page. For more information see general guidance on [paging and sorting]()
    required: false
    format: int32
    type: integer
    default: 10
    x-asee-common: true 
  page-number-param:
    in: query
    name: page
    description: Page index. For more information see general guidance on [paging and sorting]()
    required: false
    format: int32
    type: integer
    x-asee-common: true
  sort-order-param:
    description: Sort order (`asc` or `desc`). Default is asc. For more information see general guidance on [paging and sorting]()
    in: query
    name: sort-order
    type: string
    default: asc
    enum:
    - asc
    - desc
    x-asee-common: true  
  sort-by-param:  
    description: Attribute of the collection item to sort by. For more information see general guidance on [paging and sorting]().
    in: query
    name: sort-by
    type: string
    required: false
  status-param:
    description: Delivery status of the communication.
    in: query
    name: status
    required: true
    collectionFormat: csv
    enum:
      - pending
      - sent
      - delivered
      - delivery-failed
      - archived
    items:
      type: string
    type: array
  search-text-param:
    description: Search text
    in: query
    name: search-text
    required: false
    type: string
  customer-number-param:
    description: Customer number
    in: query
    name: customer-number
    required: true
    type: string
  conversation-type-param:
    description: Unique product code
    in: query
    name: conversation-type
    required: false
    collectionFormat: csv
    items:
      type: string
    type: array
  communication-id-param:
    description: The unique identifier of the communication
    in: path
    name: communication-id
    required: true
    type: string
definitions:
  communication-list:
    description: List of communications.
    allOf: 
    - $ref: '#/definitions/paged-list'
    properties:
      items:
        description: List of communication items.
        items:
          $ref: '#/definitions/communication'
        type: array
    type: object
  communication:
    description:  
      Identifies a record of the receiving or sending (or the intention to send) of a message between bank and its customers.  Content of the communication is linked to the communication record.  A communication can use any contact-medium such as a telephone call, a letter, a fax, an e-mail, electronic message, a meeting, etc. It may have occurred or be planned to occur in the future.  In each case, a discrete occurrence of a communication is identifiable. Correspondence which takes place over a period of time is not a single communication but is modeled as a series of individual related communications.
    properties:
      communication-id:
        description: Unique identifier of the communication.
        type: string
      contact:
        description: Contact information.
        $ref: '#/definitions/contact'
      customer-number:
        description: Unique identifier of the customer.
        type: string
      created:
        description:  Time and date when communication was created.
        format: date-time
        type: string
      status:
        description: Delivery status of the communication.
        enum:
          - pending
          - retrieved
          - sent
          - delivered
          - failed
          - archived
        type: string
      sent:
        description: Time and date when communication was sent.
        format: date-time
        type: string
      expires:
        description: The expiration time and date. Date and time until communication is valid.
        format: date-time
        type: string
      data:
        description: The data containing the XML document to load.
        type: string
      message-type:
        description: Type of message.
        type: string
      priority:
        description: Priority of the message.
        enum:
          - high
          - medium
          - low
        type: string
      reference-number:
        description: Provider reference number.
        type: string
      retry-count:
        description: The number of retries to send a message.
        format: int32
        type: integer
      message:
        description: Message to be sent.
        $ref: '#/definitions/message'
      conversation-type:
        description: Unique product code
        type: string
    type: object
  contact:
    description: Information about contact.
    properties:
      usage:
        description: 'Provides the context of use for this contact information. Possible values are:'
        enum:
          - seasonal
          - assistant
          - work
          - home
          - default
          - business
          - legal
        type: string
      kind:
        description: Kind of contact for direct communication receiving on.
        enum:
          - email
          - sms
        type: string
      details:
        description: Details related to contact.
        type: string
      contact-preference:
        description: Contact preferences including preferred language and list of services that customer wishes or doesn't wish to receive information for.
        $ref: '#/definitions/contact-preference'
      uri:
        type: string
    type: object
  message:
    description: Message consisting of a subject, body and attachments.
    properties:
      title:
        description: The subject of a message, should contain a few words.
        type: string
      body:
        description: Message body contains the complete content of a message and content type (text or html).
        $ref: '#/definitions/message-body'
      attachments:
        description: Content sent along with message, consists of a type of file, name and content.
        items:
          $ref: '#/definitions/message-attachment'
        type: array
    type: object
  contact-preference:
    description: Contact preferences including preferred language and list of services that customer wishes or doesn't wish to receive information for.
    properties:
      preferred-language:
        description: The language in which customer wants to receive information. 
        type: string
      opt-ins:
        description: List of services that customer wishes to receive information for.
        items:
          type: string
        type: array
      opt-outs:
        description: List of services that customer does not wishes to receive information for.
        items:
          type: string
        type: array
      uri:
        type: string
    type: object
  message-body:
    description: Message body contains the complete content of a message and content type (text or html).
    properties:
      content-type:
        description: Message content type.
        enum:
          - html
          - text
        type: string
      content:
        description: The content of a message.
        type: string
    type: object
  message-attachment:
    description: Content sent along with message, consists of a type of file, name and content.
    properties:
      content-type:
        description: The type of content that is sent as an attachment.
        enum:
          - pdf
          - excel
          - word
          - png
          - jpg
        type: string
      name:
        description: Attachment name.
        type: string
      content:
        description: Content of attachment.
        type: string
    type: object
  update-communication-status-command:
    description: Update communication status command.
    properties:
      status-code:
        description: Delivery status of the communication.
        enum:
          - retrieved
          - sent
          - delivered
          - failed
          - archived
        type: string
      status-description:
        description: Description of the communication status, e.g. the reason why communication has failed.
        type: string
    required:
      - status-code
    type: object
  command-result:
    description: Command result
    properties:
      id:
        description: Id of created, updated or deleted entity.
        type: string
      created-record-status:
        description: The created, updated, deleted record status.
        type: string
    type: object
  initiate-communication-command:
    description: The initiate communication delivery command.
    properties:
      contact:
        description: Contact information.
        $ref: '#/definitions/contact'
      message-type:
        description: Unique code of the message.
        type: string
      data:
        description: Formated or unformated data
        type: string
      template:
        description: The name of template.
        type: string
      to-channel:
        description: The channel on wich communication is sent to.
        enum:
          - email
          - sms
        type: string
      from-channel:
        description: The source from which communication is sent.
        type: string
      priority:
        description: Priority of the communication (high, medium, low).
        enum:
          - high
          - medium
          - low
        type: string
      expires:
        description: The expiration time and date. Date and time until communication is valid.
        format: date-time
        type: string
    type: object
  communication-summary-list:
    description: List of communication summaries.
    properties:
      items:
        description: List of communication summary items. 
        items:
          $ref: '#/definitions/communication-summary'
        type: array
    type: object
  communication-summary:
    description: Communication summary item contains total count, status and count of communications for each priority.
    properties:
      status:
        description: The status of communication.
        type: string
      total-count:
        description: Total number of all communications.
        format: int32
        type: integer
      high-count:
        description: Count of unread communications with high priority.
        format: int32
        type: integer
      medium-count:
        description: Count of unread communications with medium priority.
        format: int32
        type: integer
      low-count:
        description: Count of unread communications with medium priority.
        format: int32
        type: integer
    type: object
  create-document-command:
    description: The request for rendering of document.
    properties:
      data:
        description: Provides data source for document rendering.
        type: string
      format-type:
        description: 'The type of output file: pdf, excel or word.'
        enum:
          - pdf
          - excel
          - word2
        type: string
      template:
        description: Provides the name of the template for document rendering.
        type: string
    required:
      - format-type
      - template
    type: object
  document:
    description: Document content
    properties:
      data:
        description: Binary content of rendered document.
        type: string
    type: object
  paged-list:
    description: List with support for paging and sorting.
    properties:  
      total-count:
        description: Total number of items in collection.
        type: integer
      page-size:
        description: Size of the page.
        type: integer
      page:
        description: Index of current page.
        type: integer
      total-pages:
        description: Total number of pages of set size.
        type: integer
      sort-order:
        description: Sort order (`asc` or `desc`). Default is asc.
        type: string
        enum:
        - asc
        - desc
      sort-by:  
        description: Attribute of the collection item to sort by.
        type: string
responses:
  default-error-response:
    description: 'Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling]()'
schemes:
  - http
