swagger: '2.0'
info:
  description: Authorization API enables authorization of sensitive transactions initiated by actions customer by additional second factor authentication and/or involvement of other customers in authorization. Transaction authorizations are either explicitly requested by channel applications and workflows or initiated by other APIs during transaction and workflow processing.
  title: Authorization API
  version: v1
host: dev.asseco-see.rs
basePath: /authorization
tags:
  - description: Working with authorizations
    name: Authorizations
  - description: Working with mandates
    name: Mandates
  - description: Working with challenges
    name: Challenges
  - description: Working with OTP (One Time password)
    name: OTP
  - description: Working with tokens
    name: Tokens
consumes:
  - application/json
produces:
  - application/json
paths:

  /sms-otp/initiate:
    post:
      operationId: OTP_Initiate
      parameters:
        - description: Generate SMS OTP command.
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/resend-otp-cmd'
      responses:
        '200':
          description: OK
      summary: Generate One Time Password (OTP) to be used for processes that required it in validations.
      tags:
        - OTP
      x-asee-tags: []
  /orchestration-tokens:
    post:
      description: This token is used for orchestration requests
      operationId: BulkTokens_Create
      parameters:
        - description: Generate orchestration token command.
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/bulk-token-command-params'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/command-result'
        default:
          $ref: '#/responses/default-error-response'
      summary: Create orchestration tokens.
      tags:
        - Tokens
      x-asee-tags: []
parameters:
  service-code-param:
    description: Service code for this action
    in: query
    name: service-code
    required: true
    type: boolean
  async-param:
    description: Value indicating whether this request is asynchronous.
    in: query
    name: async
    required: true
    type: boolean
  page-size-param:
    in: query
    name: page-size
    description: Number of items on a page. For more information see general guidance on [paging and sorting]()
    required: false
    format: int32
    type: integer
  page-param:
    in: query
    description: Page index. For more information see general guidance on [paging and sorting]()
    name: page
    required: false
    format: int32
    type: integer
  sort-order-param:
    description: Sort order (`asc` or `desc`). Default is asc. For more information see general guidance on [paging and sorting]()
    in: query
    name: sort-order
    required: false
    enum:
      - asc
      - desc
    type: string
  sort-by-param:
    in: query
    name: sort-by
    description: Attribute of the collection item to sort by. For more information see general guidance on [paging and sorting]()
    required: false
    type: string
  include-param:
    in: query
    name: include
    description: List of fields to include in response. For more information see general guidance on [response shaping]()
    required: false
    collectionFormat: csv
    items:
      type: string
    type: array
  trim-param:
    in: query
    name: trim
    description: List of fields to trim from response. For more information see general guidance on [response shaping]()
    required: false
    collectionFormat: csv
    items:
      type: string
    type: array
  authorization-id-param:
    description: Authorization id
    in: path
    name: authorization-id
    required: true
    type: string
definitions:

  business-problem:
    example:
      type: max-attempts-reached
      title: Max authorization attempts has been reached
      details: Max authorization attempts has been reached
    properties:
      type:
        type: string
      title:
        type: string
      details:
        type: string
    type: object


  generate-challenge-cmd:
    description: Command for generating challenge
    example:
      authorization-id: AuthorizationId
    properties:
      authorization-id:
        description: Authorization Id
        type: string
    required:
      - authorization-id
    type: object
  resend-otp-cmd:
    description: Command for resending OTP
    example:
      authorization-id: 300265
    properties:
      authorization-id:
        description: Authorization Id
        type: string
    required:
      - authorization-id
    type: object
  bulk-token-command-params:
    description: Command for issuing authorization token for bulk operations that require multiple authorizations
    example:
      service-codes:
        - initiate-credit-transfer
      operations-count: 2
    properties:
      service-codes:
        description: "Service's codes list for bulk authorization"
        items:
          type: string
        type: array
      operations-count:
        description: Number of expected operations
        format: int32
        type: integer
    required:
      - service-codes
    type: object
  command-result:
    example:
      id: 20390808
      created-record-status: created
    properties:
      id:
        type: string
      created-record-status:
        type: string
    type: object
responses:
  default-error-response:
    description: 'Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling]()'
schemes:
  - http
